// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcwTnFttldZWBrxpa0G8LXHz4_Pnoo6h8',
    appId: '1:120681121636:web:9b205e48a0e14cd9d79c71',
    messagingSenderId: '120681121636',
    projectId: 'e-procurement-aja',
    authDomain: 'e-procurement-aja.firebaseapp.com',
    storageBucket: 'e-procurement-aja.firebasestorage.app',
    measurementId: 'G-H9M6V7GQYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmBxxRtvSzdco_BQNIvZEba-Wqq5Pz4k8',
    appId: '1:120681121636:android:9261b6d19bee49ded79c71',
    messagingSenderId: '120681121636',
    projectId: 'e-procurement-aja',
    storageBucket: 'e-procurement-aja.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNPPGLzgznRrj6uNVCPJkhMWHA6pmPEN4',
    appId: '1:120681121636:ios:f1a192d88eb00d87d79c71',
    messagingSenderId: '120681121636',
    projectId: 'e-procurement-aja',
    storageBucket: 'e-procurement-aja.firebasestorage.app',
    iosBundleId: 'com.example.agile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNPPGLzgznRrj6uNVCPJkhMWHA6pmPEN4',
    appId: '1:120681121636:ios:f1a192d88eb00d87d79c71',
    messagingSenderId: '120681121636',
    projectId: 'e-procurement-aja',
    storageBucket: 'e-procurement-aja.firebasestorage.app',
    iosBundleId: 'com.example.agile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcwTnFttldZWBrxpa0G8LXHz4_Pnoo6h8',
    appId: '1:120681121636:web:5df30ba4f7f459e0d79c71',
    messagingSenderId: '120681121636',
    projectId: 'e-procurement-aja',
    authDomain: 'e-procurement-aja.firebaseapp.com',
    storageBucket: 'e-procurement-aja.firebasestorage.app',
    measurementId: 'G-ZWZ6RZM4NR',
  );
}
